### PR TITLE
no age shaming

### PR DESCRIPTION
**Pull request by ImprovedTube**
if you fill in the blank, i can make another PR or commit like:  `chrome.runtime.onInstalled.addListener(function(installed){if(installed.reason=='install'){if 116 > Number(navigator.userAgent.match(new RegExp(Chrome|Firefox + '/([0-9]+)'))){alert("[Just to make sure:] Some of our features might require chrome version 116+.... _______________________") }`    ( - or rather add it precisely, when that feature is first enabled as indicated by its button or storage change.)

### CODE REVIEW

**Comment by linden0** [comment]
@ImprovedTube thanks for the contribution! i can guarantee that if chrome version isn't 116+, the extension won't work because only on 116+ can you use the keep alive strategy to keep the background script persistent during games. so when users with < 116 try to install, i feel like they shouldn't be able to because there is no way for them to play and stay updated about game events. what do you think?

**Comment by ImprovedTube** [comment]
hi @linden0    aah! 💡  https://github.com/linden0/LeetBattle/blob/18ec7f84c987e9c39a02de739ec50943dd976ba3/chrome-extension/background.js#L140-L150
 returned to manifest2 after noticing this:  https://developer.chrome.com/blog/longer-esw-lifetimes/%20%20

**Comment by linden0** [comment]
> hi @linden0 aah! 💡
> 
> https://github.com/linden0/LeetBattle/blob/18ec7f84c987e9c39a02de739ec50943dd976ba3/chrome-extension/background.js#L140-L150
> 
> returned to manifest2 after noticing [this](https://developer.chrome.com/blog/longer-esw-lifetimes/%20%20)

Isn't manifest 2 deprecated soon? or are you going to use manifest 2 as long as you can

**Comment by ImprovedTube** [comment]
btw @linden0 what do you think about? https://github.com/code-charity/Bulk-Contributor   
(the example is about browser extension language files)

**Comment by ImprovedTube** [comment]
* there is a new date to enforce mf3 in June 🤔 https://github.com/guest271314/persistent-serviceworker

**Comment by ImprovedTube** [comment]
*PS: there is a new date to enforce mf3 in June 🤔 https://github.com/guest271314/persistent-serviceworker
 (@linden0)

**Comment by ImprovedTube** [comment]
*PS: there is a new date to enforce mf3 in June 
 🤔 https://github.com/guest271314/persistent-serviceworker

will try this only for  https://github.com/code-charity/improvedtube: 
 `const keepAliveInterval = setInterval(() => chrome.runtime.sendMessage({ status: 'keep-alive' }), 29.5 * 1000);`   
 
happy 2024! @linden0

**Pull request closed without merging**
